/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as SubcontractorRouteImport } from './routes/subcontractor'
import { Route as PmRouteImport } from './routes/pm'
import { Route as InspectorRouteImport } from './routes/inspector'
import { Route as IndexRouteImport } from './routes/index'

const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const SubcontractorRoute = SubcontractorRouteImport.update({
  id: '/subcontractor',
  path: '/subcontractor',
  getParentRoute: () => rootRouteImport,
} as any)
const PmRoute = PmRouteImport.update({
  id: '/pm',
  path: '/pm',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorRoute = InspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inspector': typeof InspectorRoute
  '/pm': typeof PmRoute
  '/subcontractor': typeof SubcontractorRoute
  '/supervisor': typeof SupervisorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inspector': typeof InspectorRoute
  '/pm': typeof PmRoute
  '/subcontractor': typeof SubcontractorRoute
  '/supervisor': typeof SupervisorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inspector': typeof InspectorRoute
  '/pm': typeof PmRoute
  '/subcontractor': typeof SubcontractorRoute
  '/supervisor': typeof SupervisorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inspector' | '/pm' | '/subcontractor' | '/supervisor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inspector' | '/pm' | '/subcontractor' | '/supervisor'
  id: '__root__' | '/' | '/inspector' | '/pm' | '/subcontractor' | '/supervisor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InspectorRoute: typeof InspectorRoute
  PmRoute: typeof PmRoute
  SubcontractorRoute: typeof SubcontractorRoute
  SupervisorRoute: typeof SupervisorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subcontractor': {
      id: '/subcontractor'
      path: '/subcontractor'
      fullPath: '/subcontractor'
      preLoaderRoute: typeof SubcontractorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pm': {
      id: '/pm'
      path: '/pm'
      fullPath: '/pm'
      preLoaderRoute: typeof PmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector': {
      id: '/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof InspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InspectorRoute: InspectorRoute,
  PmRoute: PmRoute,
  SubcontractorRoute: SubcontractorRoute,
  SupervisorRoute: SupervisorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
